
set -g default-terminal "tmux-256color"

set -g mouse on
set -g extended-keys on
set -g extended-keys-format csi-u

setw -g window-status-current-format "#[reverse]  #I:#W  "
setw -g window-status-format "  #I:#W  "

set -g status-position bottom

set -g status-style "bg=colour226,fg=colour232"

set -g status-left-length 20
set -g status-left "[#{=20:session_name}] "

set -g status-right "[#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}'#{=21:pane_title}' %H:%M]"

# to update a running tmux session after making changes to this file:
# tmux source-file ~/.tmux.conf
 
# to detach a session (make it persistent):
# Ctrl + D

# to list all sessions (persistent):
# tmux ls

# to reattach to the most recently active unattached session:
# tmux attach
